apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
type: Opaque
data:
  org: ZGV2
  host: aHR0cHM6Ly91cy1lYXN0LTEtMS5hd3MuY2xvdWQyLmluZmx1eGRhdGEuY29t
  token: RFJyRy1UVnhZTEM3R0NzaTlCU2hpcFVVQ0ItUUJZU21WdGswa0VNVW1nOEFBZTdoMW1UR182N1hsLXdhaVp6REVDa09ZYlotb1B3MzhQOTFWTGtya3c9PQ==
  db: c3RvY2s=
