apiVersion: batch/v1
kind: CronJob
metadata:
  name: floats-cronjob
  namespace: stock
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: float-container
            image: artifacts.tekuro.io/floats-cronjob:latest
            env:
              - name: INFLUXDB_ORG
                valueFrom:
                  secretKeyRef:
                    name: influxdb-secrets
                    key: org
              - name: INFLUXDB_HOST
                valueFrom:
                  secretKeyRef:
                    name: influxdb-secrets
                    key: host
              - name: INFLUXDB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: influxdb-secrets
                    key: token
              - name: INFLUXDB_DB
                valueFrom:
                  secretKeyRef:
                    name: influxdb-secrets
                    key: db
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: regcred
